### ISSUE TITLE
Nebula alert support in firefox

### ISSUE THREAD

**Issue by carscx** [arsnebula/nebula-alert#1]
Hello,

I'm using nebula alert, in a polymer 2.0 element, and not working correctly in firefox. 

If I have more than 2 instances of my element. In firefox not show the third instance.

Somebody with this problem?

**Comment by chrismbeckett** [comment]
I am travelling until Thursday but can look at this once I get back. Any more detail? Does it work in Chrome or Edge, etc?

**Comment by carscx** [comment]
Thank you for your answer. 

I have upload to my static server, the build of project.

You can see in this link: https://www.carscx.com/webComp/with-alert

In both Firefox and Edge the result is the same. Show only two instances and only the first instance works fine alert. When I add nebula-alert. In chrome all works fine.

You can see in this link: https://www.carscx.com/webComp/without-alert

In Edge, Firefox and Chrome show the 3 instances of webcomponent. But the nebula-alert is not added

You can download from https://www.carscx.com/webComp/wComp.zip

You can download all project form: https://www.carscx.com/webComp/appvtwidget-loancalculator.zip

Thank you very much.

Regards,

**Comment by chrismbeckett** [comment]
Ok, well, I did find a bug in my button element where Firefox clicks were not registering which I fixed with a new patch release, but most of the problems seemed to be in your code. I was seeing lots of errors in the developer console.

1. You were importing duplicates of a bunch of the polyfills, loading by script tag in your index.html, and in your custom elements. HTML imports can dedup .html imports, but not script tags. You should really only be loading the polyfills using webcomponents-loader.js in your main index.html. Polyfills should never be loaded in your custom elements.

2. Nebula iconsets should only be defined once. When you define them in a custom element, it tries to register the iconset over and over and throws errors. I moved the iconset definition into its own file and imported it (HTML imports will de-duplicate .html imports).

3. I added a bower configuration so you can update dependencies.

Everything seems to be working now in Chrome, Firefox and IE. Here is the updated code.

https://drive.google.com/open?id=0B8NruVkcqXVvdk9wbGR6QXljWGs

**Comment by carscx** [comment]
Excelent!

Excuse me for my error code. I'm newbie in WebComponents. 

Now all it's working.

Thank you very much.
